[workspace]
resolver = "2"
members = [
  "sequencer",
  "sequencer-core",
  "sdk/rust-client",
  "examples/app-core",
  "examples/canonical-app",
  "examples/canonical-test",
  "benchmarks",
]
default-members = ["sequencer"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Deterministic sequencer prototype with low-latency soft confirmations"
homepage = "https://github.com/cartesi/sequencer"
repository = "https://github.com/cartesi/sequencer"
readme = "../README.md"
authors = [
  "Gabriel Coutinho de Paula <gcdepaula@protonmail.com>",
  "Pedro Argento <pedro.argento@gmail.com>",
  "Stephen Chen <20940639+stephenctw@users.noreply.github.com>",
]

[workspace.dependencies]
libcmt-sys = { version = "0.1", git = "https://github.com/GCdePaula/cartesi-tools-rs", rev = "786e0529cb802aa1675f6f42c06d86a302ab515b" }
trolley = { version = "0.1", git = "https://github.com/GCdePaula/cartesi-tools-rs", rev = "786e0529cb802aa1675f6f42c06d86a302ab515b" }
testsi = { version = "0.1", git = "https://github.com/GCdePaula/cartesi-tools-rs", rev = "786e0529cb802aa1675f6f42c06d86a302ab515b" }
types = { version = "0.1", git = "https://github.com/GCdePaula/cartesi-tools-rs", rev = "786e0529cb802aa1675f6f42c06d86a302ab515b" }
cartesi-machine = { version = "2", git = "https://github.com/cartesi/dave", rev = "5d0560a04f623318af9ef5b7f193170b618b6ced", features = ["download_uarch"] }
