[package]
name = "rollups-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[[bin]]
name = "devnet-stack"
path = "src/bin/devnet_stack.rs"

[dependencies]
rollups-harness = { path = "../harness" }
tracing-subscriber = { workspace = true }
app-core = { path = "../../examples/app-core" }
sequencer-core = { path = "../../sequencer-core" }
sequencer-rust-client = { path = "../../sdk/rust-client" }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
futures = "0.3"
libtest-mimic = "0.6.1"
ssz = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "process", "io-util", "signal"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
