// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

//! Build script that generates the precomputed fee table for log-space fee
//! encoding with base 129/128.
//!
//! The table contains `(129/128)^(2^i)` for i in 0..15, represented as
//! fixed-point values with 64 fractional bits stored in 4×u64 limbs
//! (little-endian, same layout as `alloy_primitives::U256`).
//!
//! All arithmetic is exact integer math — no floats, no approximation.

use std::env;
use std::fs;
use std::path::Path;

use ruint::Uint;

type U256 = Uint<256, 4>;
type U512 = Uint<512, 8>;

const FRAC_BITS: usize = 64;

/// Truncate a U512 to U256 by taking the lower 4 limbs.
/// Returns `None` if the upper 4 limbs are nonzero (value doesn't fit).
fn try_narrow(wide: U512) -> Option<U256> {
    let limbs = wide.into_limbs();
    let upper_nonzero = limbs[4] != 0 || limbs[5] != 0 || limbs[6] != 0 || limbs[7] != 0;
    if upper_nonzero {
        return None;
    }
    Some(U256::from_limbs([limbs[0], limbs[1], limbs[2], limbs[3]]))
}

/// Fixed-point multiplication: floor((a × b) >> 64).
fn fixed_mul(a: U256, b: U256) -> U256 {
    let product: U512 = a.widening_mul(b);
    let shifted = product >> FRAC_BITS;
    try_narrow(shifted).expect("fixed_mul result overflows U256")
}

/// Compute the maximum safe exponent for the fixed-point representation.
///
/// Returns the largest n such that `(129/128)^n × 2^64` fits in U256, i.e.,
/// the full fixed-point value does not overflow 256 bits.
///
/// Uses a greedy bit-by-bit approach from the most significant bit downward:
/// tentatively set each bit and check if the result still fits.
fn compute_max_exponent(table: &[U256; 15]) -> u16 {
    let fixed_one = U256::from(1u64) << FRAC_BITS;
    let mut result_exp: u16 = 0;
    let mut result_val = fixed_one;

    for i in (0..15).rev() {
        let product: U512 = result_val.widening_mul(table[i]);
        let shifted = product >> FRAC_BITS;
        if let Some(narrowed) = try_narrow(shifted) {
            result_exp |= 1 << i;
            result_val = narrowed;
        }
    }

    result_exp
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("fee_table.rs");

    // (129/128) in fixed-point: 129 × 2^64 / 128 = 129 × 2^57.
    let base_fixed = U256::from(129u64) << 57;

    // Build the table by repeated squaring.
    let mut table = [U256::ZERO; 15];
    table[0] = base_fixed; // (129/128)^1
    for i in 1..15 {
        table[i] = fixed_mul(table[i - 1], table[i - 1]);
    }

    let max_exp = compute_max_exponent(&table);

    // Generate Rust source.
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n");
    code.push_str("// Precomputed table for log-space fee encoding (base 129/128).\n");
    code.push_str("// All values are exact integer computations, no floating-point.\n\n");
    code.push_str("use alloy_primitives::U256;\n\n");

    code.push_str(&format!(
        "/// Maximum exponent whose fixed-point representation fits in U256.\n\
         /// Computed at build time: the largest n where `(129/128)^n × 2^64 < 2^256`.\n\
         pub const MAX_EXPONENT: u16 = {max_exp};\n\n"
    ));

    code.push_str(
        "/// Precomputed table: `TABLE[i]` = `(129/128)^(2^i)` in fixed-point with 64\n\
         /// fractional bits. 15 entries (bits 0..14) cover exponents 0..32767.\n\
         /// In practice exponents are capped at [`MAX_EXPONENT`].\n\
         ///\n\
         /// Generated by `build.rs` using exact integer arithmetic.\n\
         pub const TABLE: [U256; 15] = [\n",
    );

    for (i, entry) in table.iter().enumerate() {
        let limbs = entry.into_limbs();
        code.push_str(&format!(
            "    // (129/128)^{}\n    U256::from_limbs([{:#018x}, {:#018x}, {:#018x}, {:#018x}]),\n",
            1u32 << i,
            limbs[0],
            limbs[1],
            limbs[2],
            limbs[3]
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("failed to write fee_table.rs");
    println!("cargo::rerun-if-changed=build.rs");
}
