// (c) Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

//! The engine C ABI, generated by bindgen from the header. Nothing here is written by hand, so
//! to change what crosses, change the header.
//!
//! Enums arrive as plain integer constants, never Rust enums, so a value an engine adds later is
//! a number this host can refuse rather than undefined behavior. Records carry generated layout
//! assertions.

// Generated code follows C's naming and carries the whole surface, including what this host has
// no call for yet
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
