[package]
name = "canonical-test"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
authors.workspace = true

[[bin]]
name = "canonical-test"
path = "src/main.rs"

[dependencies]
app-core = { path = "../app-core" }
canonical-app = { path = "../canonical-app" }
sequencer-core = { path = "../../sequencer-core" }
ssz = { workspace = true }
testsi = { workspace = true }
types = { workspace = true }
k256 = { workspace = true }
