[package]
name = "rollups-harness"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]
app-core = { path = "../../examples/app-core" }
alloy = { workspace = true, features = ["contract", "network", "provider-anvil-api", "reqwest", "rpc-types", "signer-local"] }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
cartesi-rollups-contracts = { workspace = true }
futures-util = { workspace = true }
k256 = { workspace = true }
rusqlite = { workspace = true }
sequencer-core = { path = "../../sequencer-core" }
sequencer-rust-client = { path = "../../sdk/rust-client" }
serde = { workspace = true }
serde_json = { workspace = true }
ssz = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "process", "time"] }
tempfile = { workspace = true }
tokio-tungstenite = { workspace = true }
