[package]
name = "canonical-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
authors.workspace = true

[dependencies]
app-core = { path = "../app-core" }
sequencer-core = { path = "../../sequencer-core" }
trolley = { workspace = true }
alloy-primitives = { version = "1.4.1", features = ["serde", "k256"] }
alloy-sol-types = "1.4.1"
ssz = { package = "ethereum_ssz", version = "0.10" }

[dev-dependencies]
k256 = "0.13"
types = { workspace = true }
