[package]
name = "canonical-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
authors.workspace = true

[dependencies]
app-core = { path = "../app-core" }
sequencer-core = { path = "../../sequencer-core" }
trolley = { workspace = true }
alloy-primitives = { workspace = true }
types = { workspace = true }

[dev-dependencies]
k256 = { workspace = true }
