[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]
rollups-harness = { path = "../harness" }
sequencer-rust-client = { path = "../../sdk/rust-client" }
sequencer-core = { path = "../../sequencer-core" }
app-core = { path = "../../examples/app-core" }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
futures-util = { workspace = true }
k256 = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ssz = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util", "process", "sync"] }
tokio-tungstenite = { workspace = true }
