[package]
name = "sequencer-rust-client"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
authors.workspace = true

[dependencies]
sequencer-core = { path = "../../sequencer-core" }
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
